const mongoose = require("mongoose");
require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const Book = require("../src/models/books");

const books = [
  {
    _id: "c2517d9a-9168-403b-b194-49fdd7b53915",
    title: "1984",
    rating: 4.2,
    authorName: "George Orwell",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfBiwEVtIvgaehiCBYgip5VQJppkMlX1DDvW_ucpJ_toxICMvK3qPhD1JPv6ObNJ6kXmqVTVgXz32x6XKGDC3QmuzKbdMlv82Utn_1PuHk&s=10",
    aboutBook: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism, mass surveillance, and widespread regimentation of persons and behaviours.",
    aboutAuthor: "George Orwell was an English novelist, essayist, journalist, and critic whose workis marked by lucid prose, awareness of social injustice, and opposition to totalitarianism.",
    bookUrl: "https://www.google.co.in/books/edition/Official_Gazette_of_the_United_States_Pa/ReG6y8kmNFwC?hl=en&gbpv=1&dq=1984&pg=RA1-PA144&printsec=frontcover",
  },
  {
    _id: "eef392d1-3c60-407b-b391-6d1a74187f29",
    title: "Animal Farm",
    rating: 4,
    authorName: "George Orwell",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPOvAMLI2Tcnw5oLduUFHRHkWruJyy1sFfcHhrg6lhq9d7PNJiZeXeCrxITtvjBgF68Z76KYGO5Eq9t94DQ3i-O9OGgqUhYYeqCHYoqWIGrA&s=10",
    aboutBook: "An allegorical novella reflecting events leading up to the Russian Revolution and then on into the Stalinist era of the Soviet Union, featuring a group of farm animals who overthrow their human farmer.",
    aboutAuthor: "George Orwell was an English novelist, essayist, journalist, and critic whose workis marked by lucid prose, awareness of social injustice, and opposition to totalitarianism.",
    bookUrl: "https://www.google.co.in/books/edition/Animal_Farm/T9BUEQAAQBAJ?hl=en&gbpv=1&dq=animal+farm&printsec=frontcover",
  },
  {
    _id: "bd445ddf-d76e-452c-8314-1e83e91fe038",
    title: "A Brief History of Time",
    rating: 4.2,
    authorName: "Stephen Hawking",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbbTcURGYZvpuj0X8MwcVEsu0oKDstNjHNuwZ4rNIsC3vxEi4iuHE7s9JsWntJ-CDaxbin2HFNGvo9hS30ZeXNOI8rYydbaklgt5YmOcM&s=10",
    aboutBook: "A landmark popular science book on cosmology by physicist Stephen Hawking, exploringthe origins of the universe, space, time, black holes, and the search for a unified theory of physics.",
    aboutAuthor: "Stephen Hawking was an English theoretical physicist, cosmologist, and author who was director of research at the Centre for Theoretical Cosmology at the University of Cambridge.",
    bookUrl: "https://www.google.co.in/books/edition/A_Brief_History_Of_Time/9ysba1A1UF8C?hl=en&gbpv=1&dq=A+Brief+History+of+Time&pg=PT6&printsec=frontcover",
  },
  {
    _id: "6492a670-f13f-44ed-aa5e-af2967d086ce",
    title: "The 7 Habits of Highly Effective People",
    rating: 4.1,
    authorName: "Stephen R. Covey",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQtyd-4ahc2Vh7w8N2qTa9gk6sHWgTQUUO-0vDwvh9uA&s=10",
    aboutBook: "A self-improvement book written by Stephen R. Covey that presents a principle-centered approach for solving personal and professional problems through character ethics.",
    aboutAuthor: "Stephen R. Covey was an American educator, author, businessman, and keynote speaker best known for his immensely popular book on personal effectiveness.",
    bookUrl: "https://www.google.co.in/books/edition/The_7_Habits_of_Highly_Effective_People/020TAgAAQBAJ?hl=en&gbpv=1",
  },
  {
    _id: "0f22d1c1-b82d-45ee-98c9-1a9b3fec1301",
    title: "How to Win Friends and Influence People",
    rating: 4.2,
    authorName: "Dale Carnegie",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGj9mxJCIY24Vm2zzz2uXhpOMVDgnjnQmk0DffL42LKA&s=10",
    aboutBook: "A self-help book published in 1936 that provides timeless advice on interpersonal skills, effective communication, and building influence with others.",
    aboutAuthor: "Dale Carnegie was an American writer and lecturer and the developer of famous courses in self-improvement, salesmanship, corporate training, public speaking, and interpersonal skills.",
    bookUrl: "https://www.google.co.in/books/edition/How_To_Win_Friends_and_Influence_People/vhjXEAAAQBAJ?hl=en&gbpv=1&dq=How+to+Win+Friends+and+Influence+People&printsec=frontcover",
  },
  {
    _id: "afc89d4b-ace3-4cec-9bc1-745e504f1cf8",
    title: "The 7 Habits of Highly Effective People",
    rating: 4.1,
    authorName: "Stephen R. Covey",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKFIqqcoNh34qXoVotwiaBPAztNX7tND0O7JX1rI-wpA&s=10",
    aboutBook: "A self-improvement book written by Stephen R. Covey that presents a principle-centered approach for solving personal and professional problems through character ethics.",
    aboutAuthor: "Stephen R. Covey was an American educator, author, businessman, and keynote speaker best known for his immensely popular book on personal effectiveness.",
    bookUrl: "https://www.google.co.in/books/edition/The_7_Habits_of_Highly_Effective_People/020TAgAAQBAJ?hl=en&gbpv=1",
  },
  {
    _id: "7ce975e1-c6f7-473d-b49d-b10f1c44146f",
    title: "Atomic Habits",
    rating: 4.6,
    authorName: "James Clear",
    coverPic: "https://books.google.com/books/content/images/frontcover/fFCjDQAAQBAJ?fife=w400-h600",
    aboutBook: "A comprehensive, practical guide on how to build good habits, break bad ones, and get 1% better every day.",
    aboutAuthor: "James Clear is an author and speaker focused on habits, decision-making, and continuous improvement.",
    bookUrl: "https://www.google.co.in/books/edition/Atomic_Habits/fFCjDQAAQBAJ?hl=en&gbpv=1&dq=Atomic+Habits&pg=PT24&printsec=frontcover",
  },
  {
    _id: "f0a08de4-1d9e-4fde-a415-6386eec88b00",
    title: "Man's Search for Meaning",
    rating: 4.5,
    authorName: "Viktor E. Frankl",
    coverPic: "https://books.google.com/books/content/images/frontcover/F-Q_xGjWBi8C?fife=w400-h600",
    aboutBook: "Psychiatrist Viktor Frankl's memoir detailing his experiences in Nazi concentration camps and introducing his psychological theory of logotherapy.",
    aboutAuthor: "Viktor E. Frankl was an Austrian neurologist, psychiatrist, and Holocaust survivor.",
    bookUrl: "https://www.google.co.in/books/edition/Man_s_Search_for_Meaning/F-Q_xGjWBi8C?hl=en&gbpv=1&dq=Man%27s+Search+for+Meaning&printsec=frontcover",
  },
  {
    _id: "79c81bbc-df4a-4e59-9552-7a61e4e9b09d",
    title: "Sapiens",
    rating: 4.4,
    authorName: "Yuval Noah Harari",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe6Fz6Z3AXKv6cUCb12mK_Q3x-Lgd-lINiCKtvV-TlqA&s=10",
    aboutBook: "A survey of the history of humankind from the evolution of archaic human species in the Stone Age up to the twenty-first century.",
    aboutAuthor: "Yuval Noah Harari is an Israeli historian, philosopher, and professor in the Department of History at the Hebrew University of Jerusalem.",
    bookUrl: "https://www.google.co.in/books/edition/Sapiens_Tenth_Anniversary_Edition/MosvEQAAQBAJ?hl=en&gbpv=1&dq=Sapiens&printsec=frontcover",
  },
  {
    _id: "984412b2-f732-4e1a-97f7-1aeb4c0324be",
    title: "The Chronicles of Narnia",
    rating: 4.5,
    authorName: "C.S. Lewis",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgCUDmRt4YZSpnt9QiEqd7cdzhduoBdw0sjyIw8MXvUw&s=10",
    aboutBook: "A series of fantasy novels featuring a magical land of talking animals, mythical beasts, and a battle between good and evil.",
    aboutAuthor: "C.S. Lewis was a prolific British writer, literary scholar, and Anglican lay theologian best known for his classic children's fantasy series.",
    bookUrl: "https://www.google.co.in/books/edition/The_Chronicles_of_Narnia_Vol_I_The_Lion/6EIoDwAAQBAJ?hl=en&gbpv=1&dq=The+Chronicles+of+Narnia&printsec=frontcover",
  },
  {
    _id: "60fb98a4-9e24-464c-a40b-cf66425b4aff",
    title: "The Kite Runner",
    rating: 4.3,
    authorName: "Khaled Hosseini",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz-vwUjpOyyym53FJkRS-U8sIU_hWCnWtMwojFtA30Mg&s=10",
    aboutBook: "The story of Amir, a young boy from Kabul, and his journey toward redemption againstthe backdrop of a changing Afghanistan.",
    aboutAuthor: "Khaled Hosseini is an Afghan-American novelist, physician, and UNHCR Goodwill Ambassador.",
    bookUrl: "https://www.google.co.in/books/edition/The_Kite_Runner/KUMIEAAAQBAJ?hl=en&gbpv=1&dq=The+Kite+Runner&printsec=frontcover",
  },
  {
    _id: "da2790c7-61f8-452a-beb3-32c99a4acb98",
    title: "One Hundred Years of Solitude",
    rating: 4.1,
    authorName: "Gabriel García Márquez",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrbxmdA0BWH-Me82dZIpfFzKO-fN_30FMoT6nqOcRAiA&s=10",
    aboutBook: "A landmark magical realism novel telling the multi-generational story of the Buendíafamily in the fictional town of Macondo.",
    aboutAuthor: "Gabriel García Márquez was a Colombian novelist, short-story writer, screenwriter,and journalist, awarded the Nobel Prize in Literature in 1982.",
    bookUrl: "https://www.google.co.in/books/edition/One_Hundred_Years_of_Solitude/AfB8EAAAQBAJ?hl=en&gbpv=1&dq=One+Hundred+Years+of+Solitude&printsec=frontcover",
  },
  {
    _id: "28a7efb9-5c3d-4da0-83d0-3b16506ac062",
    title: "The Adventures of Sherlock Holmes",
    rating: 4.3,
    authorName: "Arthur Conan Doyle",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwp2cX00JZFgFf8wjbWNKu92_xkH1X-2hRQDQeowhukw&s=10",
    aboutBook: "A collection of twelve short stories featuring the brilliant consulting detective Sherlock Holmes and his loyal friend Dr. Watson.",
    aboutAuthor: "Sir Arthur Conan Doyle was a British writer and physician who created the iconic fictional character Sherlock Holmes.",
    bookUrl: "https://www.google.co.in/books/edition/Adventures_of_Sherlock_Holmes/buc0AAAAMAAJ?hl=en&gbpv=1&dq=The+Adventures+of+Sherlock+Holmes&printsec=frontcover",
  },
  {
    _id: "109c5b2c-1277-48d5-bab9-34ada9200e36",
    title: "Les Misérables",
    rating: 4.4,
    authorName: "Victor Hugo",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjiW-t2h0TCqowRFLmU8nUDZgQUJB77WkgSs00qJIdmg&s=10",
    aboutBook: "An epic historical novel following the struggles of ex-convict Jean Valjean and his quest for redemption in 19th-century France.",
    aboutAuthor: "Victor Hugo was a French poet, novelist, and dramatist of the Romantic movement.",
    bookUrl: "https://www.google.co.in/books/edition/Les_mis%C3%A9rables/fb7w8JSQN1MC?hl=en&gbpv=1&dq=Les+Mis%C3%A9rables&pg=PA28&printsec=frontcover",
  },
  {
    _id: "05a1fc18-4510-495b-9377-2aec7fbc8006",
    title: "The Count of Monte Cristo",
    rating: 4.5,
    authorName: "Alexandre Dumas",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi-tikRAab7DYdG3xs9qzLXBTrIMvPrQ840Xo6TbQObQ&s=10",
    aboutBook: "An adventure novel centering on a man who is wrongfully imprisoned, escapes, acquires a vast fortune, and exacts revenge on his betrayers.",
    aboutAuthor: "Alexandre Dumas was a French novelist whose works have been translated into nearlya hundred languages and made into numerous films.",
    bookUrl: "https://www.google.co.in/books/edition/The_Count_of_Monte_Cristo/hxxoGjkHQygC?hl=en&gbpv=1&dq=The+Count+of+Monte+Cristo&printsec=frontcover",
  },
  {
    _id: "5123d3c9-8dff-4476-bcca-70fde9d733a9",
    title: "War and Peace",
    rating: 4.2,
    authorName: "Leo Tolstoy",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIP3ccbsCNnIUTworGjzOUaD2eY3tPXs6CYIRh5xCATA&s=10",
    aboutBook: "A vast epic detailing the French invasion of Russia and the impact of the Napoleonicera on Tsarist society through the stories of five aristocratic families.",
    aboutAuthor: "Leo Tolstoy was a Russian writer widely regarded as one of the greatest authors ofall time.",
    bookUrl: "https://www.google.co.in/books/edition/War_and_peace/Ou-rdfU5t7kC?hl=en&gbpv=1&dq=War+and+Peace&pg=PA108&printsec=frontcover",
  },
  {
    _id: "c68417f2-7b8b-4250-8437-ccb055556aee",
    title: "The Brothers Karamazov",
    rating: 4.3,
    authorName: "Fyodor Dostoevsky",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS8jxw5Oa_u9FtxXN8xldxhYRM3jmHHCmlFJ2k_AqOhw&s",
    aboutBook: "A passionate philosophical novel entering deep into debates of faith, doubt, morality, and free will, centered around the murder of a corrupt landowner.",
    aboutAuthor: "Fyodor Dostoevsky was a Russian novelist, philosopher, and essayist whose literaryworks explore human psychology in the turbulent political, social, and spiritual atmosphere of 19th-century Russia.",
    bookUrl: "https://www.google.co.in/books/edition/The_Brothers_Karamazov/OG0e6djUgUYC?hl=en&gbpv=1&dq=The+Brothers+Karamazov&printsec=frontcover",
  },
  {
    _id: "637856de-11f7-4602-b7ba-91e1e5bb04cc",
    title: "Crime and Punishment",
    rating: 4.3,
    authorName: "Fyodor Dostoevsky",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMiq3_JhLotvuC2F5WQVUeReVfq_HYJ1_AcAiSQabhGg&s=10",
    aboutBook: "A psychological thriller tracking the mental anguish and moral dilemmas of an impoverished former student in St. Petersburg who plans and executes a fateful crime.",
    aboutAuthor: "Fyodor Dostoevsky was a renowned Russian novelist whose works profoundly influenced modern fiction and psychological exploration.",
    bookUrl: "https://www.google.co.in/books/edition/Encyclopedia_of_Crime_and_Punishment/rTKGPEIoRxoC?hl=en&gbpv=1&dq=Crime+and+Punishment&pg=PR33&printsec=frontcover",
  },
  {
    _id: "99a31f87-ff81-49ba-accc-89a5fe0786bd",
    title: "Frankenstein",
    rating: 4,
    authorName: "Mary Shelley",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLEya_x-VbaWwBeXOQQQ9R3SUbobvaFDNF52bXX422og&s",
    aboutBook: "A gothic science fiction novel about young scientist Victor Frankenstein, who gives life to a creature in an unorthodox scientific experiment, with tragic consequences.",
    aboutAuthor: "Mary Shelley was an English novelist who wrote the gothic novel Frankenstein and edited the works of her husband, Percy Bysshe Shelley.",
    bookUrl: "https://www.google.co.in/books/edition/Frankenstein_s_Science/sz4Yuz-E-EgC?hl=en&gbpv=1&dq=Frankenstein&pg=PA93&printsec=frontcover",
  },
  {
    _id: "c88857f3-4984-4795-88ca-61e49b085313",
    title: "The Little Prince",
    rating: 4.6,
    authorName: "Antoine de Saint-Exupéry",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDVZnxDS0ZeXWDCT8iMOd00vECIuN3GCngggAxQRpFsg&s=10",
    aboutBook: "A poetic tale of a young prince who visits various planets in space, addressing themes of loneliness, friendship, love, and loss.",
    aboutAuthor: "Antoine de Saint-Exupéry was a French writer, poet, aristocrat, journalist, and pioneering aviator.",
    bookUrl: "https://www.google.co.in/books/edition/The_Little_Prince/jM_WDwAAQBAJ?hl=en&gbpv=1&dq=The+Little+Prince&printsec=frontcover",
  },
  {
    _id: "b9985d73-617f-467d-9274-014e61e8ded2",
    title: "The Silent Patient",
    rating: 4.1,
    authorName: "Alex Michaelides",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ50MuUUgLqJaARwZR0HhpTRQ8c52m8o0ZL__f3ctuOkQ&s=10",
    aboutBook: "A psychological thriller about a woman who shoots her husband five times and then never speaks another word, and the criminal psychotherapist obsessed with uncovering her motive.",
    aboutAuthor: "Alex Michaelides is a bestselling British-Cypriot author and screenwriter.",
    bookUrl: "https://www.google.co.in/books/edition/The_Silent_Patient/a6NnDwAAQBAJ?hl=en&gbpv=1&dq=The+Silent+Patient&printsec=frontcover",
  },
  {
    _id: "123e9bc1-e974-4bdb-ac13-583add19893e",
    title: "Where the Crawdads Sing",
    rating: 4.4,
    authorName: "Delia Owens",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTitU75_88OUJPMCvz7caOZjNcXGYipYrW2-ZGHO-McMg&s",
    aboutBook: "A story centering on Kya Clark, an isolated girl who grows up in the marshes of North Carolina and becomes a suspect in a local murder investigation.",
    aboutAuthor: "Delia Owens is an American author and zoologist.",
    bookUrl: "https://www.google.co.in/books/edition/Where_the_Crawdads_Sing_Reese_s_Book_Clu/CGVDDwAAQBAJ?hl=en&gbpv=1&dq=Where+the+Crawdads+Sing&printsec=frontcover",
  },
  {
    _id: "6fba9fb8-5b52-4f6d-8d19-8c00fbc713ab",
    title: "The Fault in Our Stars",
    rating: 4.3,
    authorName: "John Green",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgLSHEiR1SkNr1RiB9CarXg4Miv817YoEQkdph_uFYMg&s=10",
    aboutBook: "A heartbreaking and witty young adult romance following Hazel Grace Lancaster, a sixteen-year-old cancer patient who falls in love with Augustus Waters.",
    aboutAuthor: "John Green is an American author, vlogger, and creator of online educational channels.",
    bookUrl: "https://www.google.co.in/books/edition/The_Fault_in_Our_Stars/Qk8n0olOX5MC?hl=en&gbpv=1&dq=The+Fault+in+Our+Stars&printsec=frontcover",
  },
  {
    _id: "e5d81d8f-db85-419e-a365-f4f7f4603259",
    title: "A Man Called Ove",
    rating: 4.4,
    authorName: "Fredrik Backman",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo6VfFvJPeZhuwogynszhg5v13V5KStI45M7C4YlAVKA&s=10",
    aboutBook: "A heartwarming comedy-drama about a grumpy, isolated old man whose rigid world is turned upside down by an eccentric young family moving in next door.",
    aboutAuthor: "Fredrik Backman is a Swedish columnist, blogger, and bestselling author.",
    bookUrl: "https://www.google.co.in/books/edition/A_Man_Called_Ove/7mtNAgAAQBAJ?hl=en&gbpv=1&dq=A+Man+Called+Ove&printsec=frontcover",
  },
  {
    _id: "faeaf52c-31cd-4cf2-9fa1-5891e6ee2355",
    title: "Normal People",
    rating: 3.8,
    authorName: "Sally Rooney",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt8doMsWdStSOXL8HIARwCBS22k5zaW9Y8z-yJTRm4vw&s=10",
    aboutBook: "A complex contemporary novel following the tender yet complicated relationship of Marianne and Connell from their high school days through their undergraduate years at Trinity College Dublin.",
    aboutAuthor: "Sally Rooney is an Irish novelist and screenwriter known for her authentic contemporary fiction.",
    bookUrl: "https://www.google.co.in/books/edition/Normal_People/x3tgDwAAQBAJ?hl=en&gbpv=1&dq=Normal+People&printsec=frontcover",
  },
  {
    _id: "d2bf8951-1c4f-4a25-be2e-9236f0bcc4a8",
    title: "Thinking, Fast and Slow",
    rating: 4.2,
    authorName: "Daniel Kahneman",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2sX60X9DDE4kf1IVPZzE74qpPkRzy6UNfNi_HGhmjtQ&s=10",
    aboutBook: "A popular science book summarizing research that explains the two systems that drivethe way we think: System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative,and more logical.",
    aboutAuthor: "Daniel Kahneman was an Israeli-American psychologist and economist notable for hiswork on the psychology of judgment and decision-making.",
    bookUrl: "https://www.google.co.in/books/edition/Thinking_Fast_and_Slow/oV1tXT3HigoC?hl=en&gbpv=1&dq=Thinking,+Fast+and+Slow&pg=PT49&printsec=frontcover",
  },
  {
    _id: "86b48883-6993-48bc-a47c-ff2c186f38b4",
    title: "Can't Hurt Me",
    rating: 4.5,
    authorName: "David Goggins",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2UcANaSEunhNlcGAa5sXuXW7Gb0DaTOUoD5gU7k2deg&s=10",
    aboutBook: "A memoir and self-help guide detailing Goggins' transformation from a depressed, overweight young man with a traumatic past into a top endurance athlete and Navy SEAL.",
    aboutAuthor: "David Goggins is a retired United States Navy SEAL, ultramarathon runner, and public speaker.",
    bookUrl: "https://www.google.co.in/books/edition/Can_t_Hurt_Me/IeYmEAAAQBAJ?hl=en&gbpv=1&dq=Can%27t+Hurt+Me&printsec=frontcover",
  },
  {
    _id: "dd2eb5d9-5a40-4045-b837-857b7bee42dd",
    title: "The 5 AM Club",
    rating: 3.9,
    authorName: "Robin Sharma",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvHtvTfl14kVqUEmBgafMw17CZTFA79Xy456iazaDIVA&s=10",
    aboutBook: "A leadership and productivity fable that emphasizes waking up early to optimize yourmornings, build personal mastery, and achieve peak performance.",
    aboutAuthor: "Robin Sharma is a Canadian writer, speaker, and leadership expert.",
    bookUrl: "https://www.google.co.in/books/edition/The_5_AM_Club/-GWBDwAAQBAJ?hl=en&gbpv=1&dq=The+5+AM+Club&printsec=frontcover",
  },
  {
    _id: "e61d9392-fcd3-42af-a4ec-95c0c9fe870e",
    title: "Ikigai",
    rating: 4.1,
    authorName: "Héctor García and Francesc Miralles",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJhRyiyy2pg9V6ttuxkpDp16MhN6fY4jv9r8R_biXxuw&s=10",
    aboutBook: "An exploration of the Japanese concept of 'ikigai'—meaning 'a reason for being'—drawing secrets of longevity and happiness from the inhabitants of Okinawa.",
    aboutAuthor: "Héctor García and Francesc Miralles are authors who specialize in Japanese cultureand philosophy.",
    bookUrl: "https://www.google.co.in/books/edition/Ikigai/MDksDwAAQBAJ?hl=en&gbpv=1&dq=Ikigai&printsec=frontcover",
  },
  {
    _id: "636a2008-2754-4f15-8970-7f48b875aa5f",
    title: "The 48 Laws of Power",
    rating: 4.2,
    authorName: "Robert Greene",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8OUH7Y55oM6BinPcVHJDMp1Snurzpuqxmy21IVCGkgQ&s=10",
    aboutBook: "A provocative and tactical guide drawing on historical philosophies to explain how power is achieved, defended, and maneuvered through human interaction.",
    aboutAuthor: "Robert Greene is an American author known for his books on strategy, power, and seduction.",
    bookUrl: "https://www.google.co.in/books/edition/The_48_Laws_Of_Power/P_zMW3EHnTEC?hl=en&gbpv=1&dq=The+48+Laws+of+Power&printsec=frontcover",
  },
  {
    _id: "e99296f5-1dc1-413d-b958-27b6d4084388",
    title: "The 4-Hour Workweek",
    rating: 3.9,
    authorName: "Timothy Ferriss",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnDaNyQKQLyV3bzwKvL3xuKOiOzxI0vBMeXMAHW-xxgA&s",
    aboutBook: "A lifestyle design guide that challenges traditional notions of retirement and work,advocating for outsourcing, automation, and minimizing hours worked.",
    aboutAuthor: "Timothy Ferriss is an American investor, author, and lifestyle entrepreneur.",
    bookUrl: "https://www.google.co.in/books/edition/The_4_Hour_Work_Week/tQ1C-rvAfJUC?hl=en&gbpv=1&dq=The+4-Hour+Workweek&printsec=frontcover",
  },
  {
    _id: "7d282943-77e4-408d-bc71-ad32b260700e",
    title: "Outliers",
    rating: 4.1,
    authorName: "Malcolm Gladwell",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWEjoF9H7eqkT1AJJs9ywFlh52WCST7Sv9UglnBIgsyw&s=10",
    aboutBook: "An examination of the factors that contribute to high levels of success, looking closely at culture, family, generation, and idiosyncratic experiences.",
    aboutAuthor: "Malcolm Gladwell is a Canadian journalist, author, and staff writer for The New Yorker.",
    bookUrl: "https://www.google.co.in/books/edition/Outlier_Detection_in_Python/56E1EQAAQBAJ?hl=en&gbpv=1&dq=Outliers&pg=PA91&printsec=frontcover",
  },
  {
    _id: "30a3c848-b54c-47c6-8ea4-678c6d08b810",
    title: "Rich Dad Poor Dad",
    rating: 4.1,
    authorName: "Robert T. Kiyosaki",
    coverPic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT32TX9t5ECUbreAyzYA9uKsfyjGzENyXPfsnQ55Eko4g&s",
    aboutBook: "A personal finance book advocating financial independence, asset building, real estate investment, and financial literacy.",
    aboutAuthor: "Robert T. Kiyosaki is an American businessman and motivational author.",
    bookUrl: "https://www.google.co.in/books/edition/Rich_Dad_Poor_Dad_What_the_Rich_Teach_Th/kRqeDwAAQBAJ?hl=en&gbpv=1&dq=rich+dad+poor+dad&printsec=frontcover",
  },
];

async function main() {
  try {
    await mongoose.connect(process.env.MONGODB_URL);
    console.log("Connected to MongoDB");

    const result = await Book.insertMany(books);
    console.log(`Successfully inserted ${result.length} books into the books collection`);
  } catch (err) {
    console.error("Error:", err.message);
  } finally {
    await mongoose.disconnect();
    console.log("Connection closed");
  }
}

main();
